Algoritmo "imparoupar"
// Disciplina  : PA        [
// Descrição   : Informar se o numero e par ou impar
// Autor(a)    : Sarah Cristina
// Data atual  : 26/07/2022
Var

numero:inteiro

Inicio
//entrada
escreval("Digite um número")
leia(numero)

//processamento
se (numero mod 2=0)entao
  escreval("Seu numero e par")
  
senao
   escreval("Seu numero e impar")
   
fimse



Fimalgoritmo