Algoritmo "volei"
// Descrição   : informar se ele pde competir ou não
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/08/2022
Var
idade:inteiro
altura:real
Inicio
// entrada
escreval("Qual sua idade?")
leia(idade)
escreval("Qual sua altura?")
leia(altura)

 se (altura < 1.75)entao
     escreval("Você está desclassificado!")

 senao entao
     escreval("Você está aprovado!")

 fimse


Fimalgoritmo