Algoritmo "inicioefim"
// Descrição   : fazer um algoritmo que escreva na tela os números de um número inicial a um número final
// Autor(a)    : Sarah Cristina Ribeiro
// Data atual  : 06/09/2022
Var
cont,acu:inteiro
num1,num2:inteiro


Inicio
escreval("Escreva o número que deseja começar")
leia(num1)
escreval("Escreva o número que deseja finalizar")
leia(num2)

para cont de 20 ate 0 faca
     acu <-acu + aont
      escreval(acu)
      
fimpara





Fimalgoritmo