Algoritmo "tabuada"
// Descrição   : fazer um algoritmo que imprima a tabuada de um número informado
// Autor(a)    :Sarah Cristina Ribeiro
// Data atual  : 06/09/2022
Var
nume,resul,cont:inteiro


Inicio
escreval("Digite o numero que deseja na tabuada")
leia(nume)

para cont de 1 ate 10 faca
     resul <- nume * cont
     escreval (nume, " x ", cont," = ",resul)

fimpara


Fimalgoritmo