Algoritmo "arearetangulo"
//Descriçaõ  :Solicita base e altura e calcula base
// Autoer    :Sarah
//Data atual :08/03/22

Var
base, alt, area:real


Inicio
// entrada
escreval("-----------------------------")
escreval("Digite a Base do Retangulo:")
leia(base)
escreval("Digite a Alturs do Retangulo:")
leia(alt)
escreval("----------------------------")

// processamento
area <- base*alt
limpatela

//saida

escreval("A area do Retangulo é:", area)



Fimalgoritmo