algoritmo "comissao"
// Função : Solicitar um algoritmo para o pagamento de comissão de vendedores
// Autor :  Sarah
// Data : 03/05/2022
// Seção de Declarações 
var
valpeca,comissao,venda,total:real
inicio
// entrada
escreval("Digte o valor da peça")
leia(valpeca)
escreval("Digte a quantidade vendida")
leia(venda)

//processamento
total <-(valpeca*venda)100*5
//saída

escreval("O valor total da comissão é:", total)
fimalgoritmo
