algoritmo "conversãominutos"
// Função : Conversão de minutos e horas em segundos
// Autor :  Sarah
// Data : 10/05/2022
// Seção de Declarações 
var
horas,seg,min,tempo:real
inicio
// entrada
escreval("Digite quantas horas trabalhou")
leia(horas)
escreval("Digite quantos minutos")
leia(min)

//processamento
tempo<-(min/60)+horas

//saída
escreval("O tempo em segundos é:", tempo)

fimalgoritmo
