algoritmo "dolar"
// Função :  Calcular a cotação do Dolar e coventer do Real para Dolar
// Autor :  Sarah
// Data : 03/05/2022
// Seção de Declarações 
var
dolar,moeda,resul:real

inicio
// início
escreval("Digite o valor do dolar atual")
leia(dolar)
escreval("Digite o valor que quer converter do dolar para o real")
leia(moeda)

//processamento
resul <-(moeda/dolar)

//saída
escreval("O valor que vai receber de dolar é:", resul)

fimalgoritmo
