algoritmo "estoquemedio"
// Função : Cacular o estoque médio de uma peça
// Autor :  Sarah
// Data : 26/04/2022
// Seção de Declarações 
var

estomin, estomax, estomedio:real

inicio
// entrada
escreval("Digite a quantidade mínina de peças")
leia(estomin)
escreval("Digite a quantidade máxima de peças")
leia(estomax)

//processamento
estomedio <-(estomin+estomax)/2

//saída
escreval("O estoque médio das peças é:",estomedio)








fimalgoritmo
