algoritmo "cacular4numeros"
// Função : Calcular o quadrado de 4 número
// Autor :  Sarah
// Data : 03/05/2022
// Seção de Declarações 
var
n1,n2,n3,n4,valor:real

inicio
// entrada

escreval("Digite o primeiro valor")
leia(n1)
escreval("Digite o segundo valor")
leia(n2)
escreval("Digite o terceiro valor")
leia(n3)
escreval("Digite oquarto valor")
leia(n4)

//processamento
valor <-(n1^2+n2^2+n3^2+n4^2)

//saída
escreval("Digite o valor total:", valor)


fimalgoritmo
